##
# シスオペ サービスアカウント(SA)を作成
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysop
  namespace: test
---
##
# シスオペSAを「クラスタロールVIEW」を対応づけ
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysop-crb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  namespace: test
  name: sysop

---
##
# シスオペ ロールの作成
#   「クラスタロールview」に含まれるので任意
#
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sysop
  namespace: test
rules:
# ポッドのアクセス権 コアAPIを指定 apiVersion: v1
- apiGroups: [""]
  resources: ["pods","pods/log","services"]
  verbs: ["get", "watch", "list"]
# deploymentのアクセス権  extention/applsを指定
- apiGroups: ["extensions", "apps"]  
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---
##
# シスオペSAと「ロールsysop」を対応づけ
#   (クラスタロール view に含まれるので任意)
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysop-rb
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sysop
subjects:
- kind: ServiceAccount
  namespace: test
  name: sysop

