apiVersion: v1
kind: Pod
metadata:
  name: web-liveness
spec:
  containers:
  - name: liveness
    image: maho/webapl:0.1
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 5